### ISSUE TITLE
📌 Clean & define organization-wide labels and milestone in Github

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#12]
## What?

Align, simplify, standardize, document and configure cross-project labels and milestones for all repositories in the blindnet-io Github organization.

## Why?

Clarify and optimize cross-project issue management:
- search/ordering/filters in projects (beta) for planning
- sync important groups like effort, priority and scopes).

## How?

- [x] standardize, align and document labels
- [x] use the ~~[org-labels](https://github.com/repo-utils/org-labels) CLI tool~~  [github-label-sync](https://github.com/Financial-Times/github-label-sync) and [label_sync](https://github.com/kubernetes/test-infra/tree/master/label_sync) to clean labels in existing repos
- [x] define the milestones we need (@noelmace, @filipblnt & @milstan): good opportunity to sync DevRel & Com planning with the Engineering one :arrow_right: https://github.com/blindnet-io/communication-management/issues/128#issuecomment-1143707438
- [x] [update default labels for future repositories in the organization](https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization)
- [x] use [a script or web app](https://dev.to/hardiksondagar/how-to-create-cross-repository-milestones-in-github-423o) to duplicate milestones between repositories (cross-project milestones [aren't supported yet](https://github.com/github/roadmap/issues/276))

**Comment by noelmace** [comment]
@filipblnt Would be kind enough to make a quick PR in the .github project for that and then run the CLI again on all projects, please ? This would allow us to directly check the second box in the task-list and focus on milestones. If you don't have time for that, no worry, we'll just need to wait a little more.

**Comment by noelmace** [comment]
As I can't find any solution to link the default labels for new repositories, I'll simply manually remove/update the basic once, and recommend we use github-label-sync to add the others systematically.

**Comment by noelmace** [comment]
Done :heavy_check_mark: 

Following https://github.com/blindnet-io/.github/pull/5, I used the command and configuration in https://github.com/blindnet-io/.github/pull/6 to update labels in "all" repositories.

Next time (meaning, when I'll have time to actually write a good Node script for that), we should list additional labels we actually use in specific repositories so we can remove the `allow-added-labels` option and automatically delete the labels we don't want.

Also, I don't think the `env:...` labels are useful in management repositories (except product-management obviously).

**Comment by noelmace** [comment]
I [updated the default labels for future repositories in the organization](https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization) to be the minimum following https://github.com/blindnet-io/devrel-management/issues/12#issuecomment-1144960843.
