### ISSUE TITLE
📑 [Epic]: Dev Workflow & Tools for v2

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#18]
## Description

Define a clear and thorough frame for all v2 related developments (PR, DoD, etc.)

### Context

This has been discussed with @filipblnt during a meeting on 2022-05-19. As Privateform and devkit v1 are "temporal / soon to be legacy" projects, defining thorough tooling, guidelines and frame for them right now don't have a good enough ROI.

This Epic will therefore be our first priority after having defined the conceptualisation for the v2, so we can be sure to do everything correctly.

### Intended outcome

All development of devkit is naturally guided to the respect of good practices, therefore improving our productivity and avoiding misunderstandings and errors.

## Sub-tasks

- [ ] https://github.com/blindnet-io/devrel-management/issues/5
- [x] https://github.com/blindnet-io/devrel-management/issues/20
- [x] https://github.com/blindnet-io/blindnet-docs/issues/4
- [x] https://github.com/blindnet-io/devrel-management/issues/6
- [ ] https://github.com/blindnet-io/product-management/pull/897

## Stakeholders

- @filipblnt leading the project
- @blindnet-io/engineering implements
- @noelmace for guidance and assistance

**Comment by noelmace** [comment]
Main goals have been met, as our dev workflow and tools for the devkit are sufficient for our current needs.

As indicated in https://github.com/blindnet-io/product-management/pull/897 and https://github.com/blindnet-io/devrel-management/issues/5#issuecomment-1253727534, several related topics don't need to be addressed right now. We are still continuously improving our DevX and workflows. Related issues don't need to be tracked in a specific epic anymore.
