### ISSUE TITLE
📑 [Epic]: update blindnet-io/bllindnet-docs

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#28]
## What?

First global improvement of the documentation.

## How?

The simplest solution could be to move quickly to another tool with some nice default template, like [mdbook](https://rust-lang.github.io/mdBook/), [docusaurus](https://docusaurus.io/), [docsify](https://docsify.js.org/) or [Rocket](https://rocket.modern-web.dev/).

And of course, we need a nicer homepage.

- [x] blindnet-io/communication-management#34
- [x] blindnet-io/communication-management#58
- [x] https://github.com/blindnet-io/blindnet-docs/issues/2
- [x] blindnet-io/devrel-management#31
- [x] https://github.com/blindnet-io/blindnet-docs/issues/7
- [x] https://github.com/blindnet-io/blindnet-docs/issues/11
- [ ] https://github.com/blindnet-io/blindnet-docs/issues/10
- [x] https://github.com/blindnet-io/blindnet-docs/issues/4

**Comment by filipblnt** [comment]
@noelmace Regarding [homepage improvement](https://github.com/blindnet-io/blindnet-docs/issues/7), you mentioned a while ago that you plan to do it, do you still think you could contribute there?

**Comment by noelmace** [comment]
This is my fourth priority in my backlog after https://github.com/blindnet-io/communication-management/issues/111 and 2 other issues that are actually pretty broad and could overlap with early Q3. I believe I can do it this week, but it could be a good idea for you to start a quick draft PR so I can see what you have in mind if you can/want.

**Comment by noelmace** [comment]
https://github.com/blindnet-io/blindnet.dev/issues/10 is now tracked in https://github.com/blindnet-io/devrel-management/issues/48 and all other sub-tasks have been addressed
