### ISSUE TITLE
📑 [Epic]: Tech Events - S2 2022

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#35]
## Description

All Tech Events related stuff for S2 2022 (from Jully to December).

### CFPs

- [ ] [Open Source Experience 2022](https://sessionize.com/open-source-experience-2022/): Until 2022-06-16
- [ ] [Devfest Nantes](https://conference-hall.io/public/event/CfucIjaXxrZThJE0POR3): Until 2022-06-19
- [ ] [Forum PHP](https://afup.org/event/forumphp2022): Until 2022-06-20
- [ ] [Agile Tour Toulouse](https://sessionize.com/agile-tour-toulouse-2022/): Until 2022-06-26
- [ ] [Devfest Strasbourg 2022](https://conference-hall.io/speaker/event/wgaja45IBdGT4sw4CXDB): Until 2022-06-30
- [ ] [Devoxx Morocco](https://dvma22.cfp.dev/#/login): Until 2022-07-15
- [ ] [BDX I/O 2022](https://conference-hall.io/public/event/OJC5Ou5YJodfetgSJCa3): Until 2022-07-31
- [ ] [Agiletour bordeaux](https://sessionize.com/agile-tour-bordeaux-2022/): Until 2022-07-31

### Talks

- [ ] :artist:  Draw me like one of your web browsers
- [ ] :fist_raised: La revanche Bisounours _(titre temporaire)_
- [ ] :book: (Quicky) Confinement: le livre dont vous êtes la victime
- [ ] :notes: Faut-il perdre tout espoir... dans le Web?
- [ ] :artist: (2) Il était une fois... la frugalité _(titre temporaire)_

### Conferences

> TBD

### Sponsoring

> TBD

**Comment by noelmace** [comment]
For now, only LunaConf and PHP Forum selected me (with my co-speaker) to give a talk during S2 2022: https://github.com/blindnet-io/devrel-management/issues/40

TODO:

- We'll soon stop proposing https://github.com/blindnet-io/devrel-management/issues/40, and need a successor. https://github.com/blindnet-io/devrel-management/issues/43 wasn't a good enough idea, so we'll see if https://github.com/blindnet-io/devrel-management/issues/78 can be a better candidate.
- I believe https://github.com/blindnet-io/devrel-management/issues/41 and https://github.com/blindnet-io/devrel-management/issues/42 were only a one-time thing as no other event seems interested
- We need to find a better title and abstract for https://github.com/blindnet-io/devrel-management/issues/38

However, the DevKit adoption is now my main focus (with workshops, etc.), before awareness. Such contents might not be suitable for such events for now (product promotion / not enough "generic" material to share), but I'll still see if I can write an abstract to answer CFPs and get feedback.

As this is an epic for the whole 2nd semester, I'm moving it to the Q4 milestone.
