### ISSUE TITLE
📌 update and share event tracking document

### ISSUE THREAD

**Issue by nweldev** [blindnet-io/devrel-management#39]
## What?

Update and reuse my event tracking spreadsheet for blindnet.

## Why?

- track conferences for CFP, sponsoring and attendance
- manage technical events as a team (w/ @timnicblind)
- help writing the internal newsletter

## How?

- [ ] Reuse discussions in Discord, other projects, CFP platform and mailing lists to update the event list
- [ ] remove useless sheets and information
- [ ] move to the blindnet's Google Org and share with everyone

**Comment by nweldev** [comment]
https://github.com/blindnet-io/devrel-management/issues/97 reduce my need for my previous thorough tracking document that would take a lot of time to update and adapt. I'm therefore postponing this to Q4 for now.

**Comment by noelmace** [comment]
I don't use this document anymore as it wasn't efficient enough to justify maintaining it for a single person.
