### ISSUE TITLE
🔴 [Epic]: complete and promote incentives to use and contribute to blindnet devkit

### ISSUE THREAD

**Issue by nweldev** [blindnet-io/devrel-management#48]
## Description

Follow a coherent content strategy to engage third-party developers in using and contributing to the devkit.

### Intended outcome

- Third-party developers do not encounter any friction between the first time they hear about the devkit and a first contribution.
- The dev community is aware of the devkit, what it stands for, how it can concretely help them, and why they should contribute to it.
- Third-party developers can quickly identify how they can use the devkit in a real project.
- Third-party developers can quickly identify simple contributions to make.

## Progress tacking

- [x] https://github.com/blindnet-io/communication-management/issues/153
- [x] https://github.com/blindnet-io/product-management/issues/721
- [ ] https://github.com/blindnet-io/communication-management/issues/150

> _remainders_
> 
> - [x] https://github.com/blindnet-io/communication-management/issues/160#issuecomment-1253521632

### Docs / blindnet.dev

> blindnet.dev is the central entry point and ref for third-party developers.
> We need to improve it so it includes all required pieces of information and gives enough incentives to contribute.

- [x] https://github.com/blindnet-io/devrel-management/issues/66
- [x] https://github.com/blindnet-io/devrel-management/issues/50
- [x] https://github.com/blindnet-io/blindnet.dev/issues/26
- [x] #62
- [x] https://github.com/blindnet-io/product-management/issues/773
- [x] https://github.com/blindnet-io/devrel-management/issues/7
- [x] https://github.com/blindnet-io/communication-management/issues/158

> _remainders_
> 
> - [ ] https://github.com/blindnet-io/blindnet.dev/issues/10
> - [ ] https://github.com/blindnet-io/blindnet.dev/issues/18
> - [ ] https://github.com/blindnet-io/blindnet.dev/issues/14
> - [ ] https://github.com/blindnet-io/blindnet.dev/issues/21

### Activation

- [x] https://github.com/blindnet-io/devrel-management/issues/46
- [x] https://github.com/blindnet-io/communication-management/issues/134

> _remainders_
> 
> - [ ] https://github.com/blindnet-io/devrel-management/issues/60

#### Generate Early Traction

- [ ] https://github.com/blindnet-io/communication-management/issues/165
- [x] https://github.com/blindnet-io/communication-management/issues/166
- [ ] https://github.com/blindnet-io/communication-management/issues/164

### Content creation

> The following is simply a list of ideas. These aren't prioritized, and some may not be addressed.
> More important content should be created following the development of the devkit and added here as we go.

- [x] https://github.com/blindnet-io/devrel-management/issues/25
- [x] https://github.com/blindnet-io/openness-framework/issues/20

> _remainders_
> 
> - [ ] introduction videos
> - [ ] https://github.com/blindnet-io/devrel-management/issues/26
> - [ ] https://github.com/blindnet-io/devrel-management/issues/44
> - [x] https://github.com/blindnet-io/communication-management/issues/117
> - [ ] https://github.com/blindnet-io/devrel-management/issues/14

> _outdated_
>
> - [ ] #63
> - [ ] https://github.com/blindnet-io/devrel-management/issues/23
> - [ ] https://github.com/blindnet-io/devrel-management/issues/34
> - [ ] twitch recurring series on Trust
> - [ ] https://github.com/blindnet-io/devrel-management/issues/36

### Improve OSS DevX (issues and dev)

- [x] https://github.com/blindnet-io/devrel-management/issues/20
- [x] https://github.com/blindnet-io/devrel-management/issues/2
- [x] https://github.com/blindnet-io/product-management/issues/771
- [x] https://github.com/blindnet-io/staff-management/issues/12
- [x] https://github.com/blindnet-io/devrel-management/issues/9

> _remainders_
>
> - [x] complete all OSP checklists _(actually a background task, good enough for our current needs)_
> - [ ] https://github.com/blindnet-io/devrel-management/issues/5

### Communities, outreach and partnerships

- [ ] https://github.com/blindnet-io/devrel-management/issues/21
- [x] https://github.com/blindnet-io/communication-management/issues/17
- [x] https://github.com/blindnet-io/communication-management/issues/131

> _remainders_
> 
> - [x] https://github.com/blindnet-io/devrel-management/issues/37
> - [x] https://github.com/blindnet-io/devrel-management/issues/1

## Stakeholders

- @noelmace to define and follow the strategy
- @milstan and @Vuk-BN to track progress, help identify priorities and raise warnings if necessary
- @blindnet-io/engineering to feed @noelmace with features and contents, give feedback, accompany third-party contributors and implement DevX improvements
- @timnicblind and @MRPbdnt to help promote content and progress

**Comment by milstan** [comment]
@noelmace could I ask you please, to review this list of subtasks and close the ones that have been acheived, so that we have a clear picture on the milestone closing date Sept 22.

**Comment by noelmace** [comment]
@milstan I believe all related issues are now up to date. I also updated this epic's description to make a clear difference between:
1. what we still expect to be done in the next few weeks (slightly behind schedule)
2. remainders to move to Q4 or no milestone
3. outdated issues

**Comment by noelmace** [comment]
> **Note** (for myself)
>
>  [list of my remaining issues for Q3](https://github.com/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Q3+2022%22+assignee%3Anoelmace)
