### ISSUE TITLE
twitch "episode 0"

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#63]
First "episode" on Twitch to get things started.

The idea is to "play dumb" while "trying" to do my first stream on Twitch, doing mistakes, and other more experienced people to intervene to explain to me how to do better

This "episode", and therefore the following comments, will be in french to include all participants.

**Comment by noelmace** [comment]
Date prévue: vendredi 22 à 18h

## Déroulement

1. intro
2. appel de @m4dz via une application de VC (à déterminer)
3. @m4dz explique VDO.ninja
4. @fteychene rejoint via vdo.ninja et "fait la leçon" sur OBS
5. @gouz puis @Akanoa viennent discuter de "lancement sur Twitch", orga et complexe de l'imposteur
6. @bdauvissat: "au fait, t'as pensé à éditer le truc pour le partager plus tard"
7. transition @gouz: récupérer la vidéo sur Twitch
8. @bdauvissat: rapide intro à Da Vinci
9. conclusion / teasing

## TODO

- [ ] confirmer avec tout le monde
    - [ ] @m4dz
    - [ ] @fteychene
    - [ ] @gouz 
    - [ ] @Akanoa
    - [ ] @bdauvissat
- [ ] préparer et tester OBS et matos avant le live
- [ ] installer [Da Vinci](https://www.blackmagicdesign.com/fr/products/davinciresolve)
- [ ] déterminer application de VC à utiliser avec @m4dz
- [ ] déterminer application de chat à utiliser avec tout le monde
- [ ] rapide teasing sur Twitch (pour avoir une vidéo à dl et éditer durant (7) et (8))
- [ ] annonce sur Twitter le 2022-07-21 à 18:00 CET
- [ ] rappel sur Twitter le 2022-07-22 à 12:00 CET et 17:30 CET

**Comment by noelmace** [comment]
We had to postpone this until further notice as I wasn't available on Monday.

**Comment by noelmace** [comment]
Closing as this isn't relevant anymore (I'll find another way to get started on twitch if necessary).
