### ISSUE TITLE
"blindnet devkit" branding

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#7]
## What?

Create a brand (name and logo) for our dev tools (SDK & Backend).

## Why?

The absence of a clear designation for our dev tools creates confusion and complexifies any promotion effort.

## How?

- [x] find a name collectively
- [ ] https://github.com/blindnet-io/devrel-management/issues/9
- [ ] #83
- [ ] #84
- [ ] use the logo in README files and the documentation

**Comment by noelmace** [comment]
<h3 align=center>clearly define which projects constitute a coherent "dev solution/framework" when put together, and how</h3>

---

Let's start by listing the associated repositories:

| repo | open | description |
|-|-|-|
| [blindnet-docs](https://github.com/blindnet-io/blindnet-docs) | early May | documentation & entry point
| [blindnet-sdk-js](https://github.com/blindnet-io/blindnet-sdk-js) | :heavy_check_mark: (to be improved) | JavaScript SDK for web frontend development
| [blindnet-sdk-php](https://github.com/blindnet-io/blindnet-sdk-php) | :heavy_check_mark: (to be improved) | PHP SDK for web development
| [blindnet-backend](https://github.com/blindnet-io/blindnet-backend) | Jun | Open Core Server (C#)
| [blindnet-backend-scala](https://github.com/blindnet-io/blindnet-backend-scala) | TBD |  alternative Open Core Server
| [dotnet-sdk](https://github.com/blindnet-io/dotnet-sdk) | TBD | TBD
| [blindnet-sdk-dotnet-core-server](https://github.com/blindnet-io/blindnet-sdk-dotnet-core-server) |  TBD | TBD

### TBD by @blindnet-io/engineering

- [ ] add a comment to propose a thorough description for each of these projects and soft deadlines for making "TBD open" repos public
- [ ] https://github.com/blindnet-io/communication-management/issues/107
- [ ] optionally (but would be really great) provide a schematic explaining how all of them interact with each other

We'll then progressively improve the documentation together to make sure outsiders easily get a clear broad understanding of what "blindnet devkit" exactly means.

### Docs

blindnet-docs will be opened right after https://github.com/blindnet-io/blindnet-docs/pull/3

Cf. https://github.com/blindnet-io/devrel-management/issues/3

**Comment by noelmace** [comment]
<h3 align=center>rename all projects</h3>

---

IMHO, we should:

- invert language and type (e.g. _blindnet js SDK_) to avoid any confusion with the previous informal "blindnet SDK" branding
- replace backend with server for more clarity and to reflect our Open Core approach

Then, we can use, depending on the context (i.e. whatever is clearer):

- _blindnet devkit {language} {type}_ (e.g. the blindnet devkit JS SDK)
- _blindnet {language} {type}_ (e.g. blindnet JS SDK)

IMHO, repositories' names should keep using (2), while the README titles and repo description should use (1) (e.g. ***blindnet devkit - JavaScript SDK***)

**Comment by noelmace** [comment]
Comments defining the following technical tasks for @blindnet-io/engineering have been moved to a dedicated Epic (#9) and a subtask issue (#10) for more clarity.

This issue will now focus on following these overall efforts, and the branding itself (e.g. logo).

**Comment by filipblnt** [comment]
> we'll use blindnet xxx by default for all products, except PrivateForm

What about blindsend, I believe it was said that the name remains as it is ?

**Comment by Vuk-BN** [comment]
I have chatted with a number of investors and shared the name 'devkit' which did not resonate with them. I had to explain, in some fashion, what we mean by devkit - a set of tools (SDKs, APIs, web components) - a developer can implement into their tack stack. 

I got feedback that non-technical folks (think investors, decision makers excluding CTOs) think of tech service offering in terms of 'something-as-a-service' or tools (stack of tools).

And that is when it hit me. Why don't we co-brand _blindnet devkit_ also as 

**Privacy Stack**

Since the messaging needs to be resonate with the audience we are presenting, a stack of tools for privacy is something people can grasp. This 'stack of tools', ie Privacy stack, is ultimately blindnet devkit.

**Comment by noelmace** [comment]
@Vuk-BN Makes perfect sense :+1: 

I believe"Privacy Stack" and "blindnet devkit" should designate two slightly different (even if strongly related) approaches:
- "devkit" put the emphasis on what the developers use on a daily basis (SDKs especially), on which we don't make money directly
- "stack" put the emphasis on services (SaaS especially), which is strongly linked with our Open Core strategy, with an associated marketing mix (including, of course, prices)
- "Privacy Stack" may include use cases that don't impact developers directly, but other personas, like DPOs and data managers, and developers should still have these use cases in mind

In other words, "Privacy Stack" focuses on the **services**, while "blindnet devkit" focuses on the **tools**.

https://github.com/blindnet-io/blindnet-backend-scala, for example, should be part of the devkit as an open-core server you can run by yourself (for tests etc.) **AND** part of the privacy stack as a SaaS service with an attractive price, better and simpler experience overall, in part thanks to our proprietary extensions.

As a consequence, I believe this "Privacy Stack" branding can also be part of our communication strategy for developers. Like I said, I don't think this should designate the _"same set of tools and services branded as blindnet devkit"_ exactly.

However, having two different brands to manage closely related things can be very difficult, leading to confusion and communication errors.

I'd recommend focusing on the DevKit brand for now (using "Privacy Stack" in dedicated contexts only, as @Vuk-BN suggested), and progressively moving toward the "Privacy Stack" brand as we build and deliver new services.

**Comment by Vuk-BN** [comment]
@noelmace I agree completelly with everything you said (ie wrote). Privacy stack is a term that non-technial stakeholders can grasp and can wrap their heads around - they now what the term 'privacy' means, and they are also familiar with the term 'stack' as in stack of tools or services their digital products/applications use. 

I also agree that for now we need to keep the branding simple - go with blindnet devkit. That said, in my investor presentation, I am introducing the concept of 'Privacy Stack' that is excatly what you pointed out: blindnet devkit + services (DPO-as-a-service, training, consulting).

Once we get to discuss our brand redesign - website, marketing materials, communication (prob. at the end of Q3), we will revisit this discussion on who we target, where and with what message.

**Comment by noelmace** [comment]
#9 went out of the scope defined by this specific epic and conveid most related effort, but will soon be closed - see https://github.com/blindnet-io/devrel-management/issues/9#issuecomment-1253699050

I now believe the blindnet devkit branch is sufficiently defined, and the initial goal to have a "clear designation" has been met.
I'm therefore closing this epic, as it doesn't serve any specific purpose anymore (issues for following actions have been created and don't need an epic).

- #83 is still necessary, but with a lower priority than most contents currently plan for blindnet.dev
- #84 has a low priority, and needs to be discussed with @Vuk-BN
