### ISSUE TITLE
📑 [Epic]: clearly define which projects constitute a coherent "dev solution/framework" when put together, and how

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/devrel-management#9]
Let's start by listing the associated repositories:

| repo | open | description |
|-|-|-|
| [blindnet-docs](https://github.com/blindnet-io/blindnet-docs) | early May | documentation & entry point
| [blindnet-sdk-js](https://github.com/blindnet-io/blindnet-sdk-js) | :heavy_check_mark: (to be improved) | JavaScript SDK for web frontend development
| [blindnet-sdk-php](https://github.com/blindnet-io/blindnet-sdk-php) | :heavy_check_mark: (to be improved) | PHP SDK for web development
| [blindnet-backend](https://github.com/blindnet-io/blindnet-backend) | Jun | Open Core Server (C#)
| [blindnet-backend-scala](https://github.com/blindnet-io/blindnet-backend-scala) | TBD |  alternative Open Core Server
| [dotnet-sdk](https://github.com/blindnet-io/dotnet-sdk) | TBD | TBD
| [blindnet-sdk-dotnet-core-server](https://github.com/blindnet-io/blindnet-sdk-dotnet-core-server) |  TBD | TBD

### Steps

- [ ] add a comment to propose a thorough description for each of these projects and soft deadlines for making "TBD open" repos public
- [ ] https://github.com/blindnet-io/communication-management/issues/107
- [ ] optionally (but would be really great) provide a schematic explaining how all of them interact with each other

We'll then progressively improve the documentation together to make sure outsiders easily get a clear broad understanding of what "blindnet devkit" exactly means.

### Docs

blindnet-docs will be opened right after https://github.com/blindnet-io/blindnet-docs/pull/3

**Comment by filipblnt** [comment]
I've updated the original issue description with the complete list of repositories.

**Comment by filipblnt** [comment]
Description is updated again with links to the code repositories that currently constitute "dev solution". Each of the repository now has:

- An issue titled `OSS checklist` containing the checklist as defined [here](https://github.com/blindnet-io/openness-framework/tree/main/OpenSource/checklists). All checkboxes that apply at the current moment have been checked, however verification would be good.
- A basic README, either in the develop/main branch if it already existed there, or in the new `devrel-readme` branch. 

@noelmace As you know we are working on the product and we are already a bit late on that so I need to concentrate fully on the devkit in order to start the development asap. Therefore I need you to help here, especially with the [README files](https://github.com/blindnet-io/devrel-management/issues/19#issuecomment-1146087179) of internal team repos, and [docs](https://github.com/blindnet-io/devrel-management/issues/28). Of course I'm available for any info you need and will get back to this whenever I have space, but we need to rely on you in order to have these things prepared.

**Comment by noelmace** [comment]
Just added [blindnet-client-javascript-example](https://github.com/blindnet-io//blindnet-client-javascript-example) as it is the first thing developers see when starting the quick start guide.

Please add at least a minimal description in all READMEs, and I'll do the rest.

**Comment by noelmace** [comment]
@filipblnt except if you have any reason to keep them private, I propose to add a [MIT](https://github.com/blindnet-io/openness-framework/blob/main/docs/decision-records/DR-0001-oss-license.md) [LICENSE file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to all the listed repositories and to make all of them public right away (i.e. on 2022-06-20, except maybe for [blindnet-backend-scala](https://github.com/blindnet-io/blindnet-backend-scala)).

Even if the READMEs aren't done yet, it would still be better to have all tools available for community members to better understand the devkit. Plus, it would be a good incentive for us to document them ASAP.

**Comment by filipblnt** [comment]
Ok for the MIT license. 

As for making the repos public, please keep the following ones private for a few more days (we still need to fix a few things there) and I'll let you know when they are ready:

- dashboard-web-client
- identity-api
- gateway
- privateform-web-client
- privateform-server

**Comment by noelmace** [comment]
I added the missing LICENSE files in most repositories (using the default branch, which sometimes was `develop`), made them public, and updated this issue's description accordingly.

**Comment by noelmace** [comment]
**NB:** we should also add a second license (CC by-sa) for the content of  "Management" and documentation projects.

**Comment by noelmace** [comment]
@filipblnt Please act on or discuss my comments on projects' names here:
- https://github.com/blindnet-io/quickstart-token-generator-javascript/pull/2#issuecomment-1163129685
- https://github.com/blindnet-io/quickstart-client-javascript-example/pull/3#issuecomment-1163107637
- https://github.com/blindnet-io/dashboard-web-client/pull/2#issuecomment-1163092595

**Comment by noelmace** [comment]
Just added password-assistant to the list.

Up @blindnet-io/engineering

**Comment by noelmace** [comment]
Co-assigned to @m4rk055 instead of @filipblnt: we need to get this done right after prep DevKit v0

**Comment by noelmace** [comment]
The followings still have to be addressed by @blindnet-io/engineering:

- [ ] https://github.com/blindnet-io/sdk-java-client/pull/42
- [ ] https://github.com/blindnet-io/sdk-java-server/pull/2
- [ ] https://github.com/blindnet-io/sdk-dotnet-core-server/pull/2
- [ ] https://github.com/blindnet-io/sdk-dotnet-framework-server/pull/2
- [ ] up-to-date LICENSE and README file on all projects' default branch
    - I'd expect `main` to be the default branch for most projects - project's with README column set to `develop` in the above table should have their develop branch merged into main
    - only highly experimental projects should use `develop` as default, if and only if necessary (v0 semver on main branch is expected to be used instead): if needed, add a comment to list those repositories
- [ ] update the names of the repos marked with a :x: according to discussions
- [ ] make [dashboard-web-client](https://github.com/blindnet-io/dashboard-web-client), [identity-api](https://github.com/blindnet-io/identity-api) and [gateway](https://github.com/blindnet-io/gateway) public
- [ ] make sure no repo is missing in the table
- [ ] make sure all [Github repo descriptions](https://docs.github.com/en/get-started/quickstart/create-a-repo#create-a-repository) are coherent and up to date

**Comment by TheKinrar** [comment]
> make [dashboard-web-client](https://github.com/blindnet-io/dashboard-web-client), [identity-api](https://github.com/blindnet-io/identity-api) and [gateway](https://github.com/blindnet-io/gateway) public

identity and gateway (and also backend but we're not aiming at making this one public) both contain many secrets and keys, so we'll need to:
1. fix this by removing the secrets and keys (and make it clear to Fusion they need to stop adding secrets to the repos)
2. as git has history, we'll need to identify and change all leaked secrets
this will probably take some time, especially 2., and needs to be done very carefully

**Comment by noelmace** [comment]
Ok so let's just postpone [this](https://github.com/blindnet-io/devrel-management/issues/9#issuecomment-1180442952) for now.

**Comment by m4rk055** [comment]
Probably same for [privateform-web-client](https://github.com/blindnet-io/privateform-web-client) and [privateform-server](https://github.com/blindnet-io/privateform-server).

**Comment by noelmace** [comment]
I update the steps in the description accordingly.

**Comment by noelmace** [comment]
@m4rk055 I see you removed the :x: before repos' names, but didn't change the actual names of the repo according to https://github.com/blindnet-io/devrel-management/issues/9#issuecomment-1163205722.

Please give your justifications below. If this needs further discussion to reach a consensus, we'll simply move this to a new issue / DR update in Q3.

**Comment by m4rk055** [comment]
Missed the comment, repo names changed now.

**Comment by noelmace** [comment]
I added a TODO list for each remaining Readme PR.

**Comment by noelmace** [comment]
There has been huge progress on this matter, thanks to @blindnet-io/engineering especially :+1: 

Lots of things has changed since this issue has been written (especially, priorities of any topics related to the blindnet Encryption Engine and other pre-existing projects that doesn't currently fit into the devkit scope). As it impact many aspects of our development and docs process, the discussion and actions went in several complementary directions. This notably complexified this issue itself.

I now believe we are in a good enough state regarding this particular issue. 
I'll still need to soon conduct an overall rewiew to clarify and close it.

**Comment by noelmace** [comment]
## Naming

The former "blindnet devkit ... SDK" for encryption and user management is now named "blindnet encryption engine" (see https://blindnet.dev/docs/encryption/) to emphasise that these components are NOT part of the DevKit.

The encryption part of the DevKit will be addressed in the future. It hasn't been yet formally decided if the pre-existing components of the blindnet encryption engine will or will not be reused for that, but for now, it seems we won't (ping @blindnet-io/engineering if I'm wrong).

## Proprietary Projects

We still have 6 private repositories:

- [dashboard](https://github.com/blindnet-io/dashboard-web-client): will soon be rewritten to be compatible with the DevKit. For now, we intend to keep it proprietary, but this might change later on when we'll actually define the exact business model and SaaS offering. See https://github.com/blindnet-io/blindnet.dev/pull/49: « Following our [Open Core](https://github.com/blindnet-io/openness-framework/blob/main/docs/refs/business-models.md#open-core) model, the blindnet dashboard is delivered as a proprietary paid service. »
- privateform v1 related projects - no formal decision has been taken, but for now, we informally agreed those shouldn't be open sourced
    - [identity-api](https://github.com/blindnet-io/identity-api): readme and license are OK (see https://github.com/blindnet-io/identity-api/pull/6), but [2 PRs](https://github.com/blindnet-io/identity-api/pulls) are waiting to be merged since June
    - [gateway](https://github.com/blindnet-io/gateway): readme and license are OK (see https://github.com/blindnet-io/gateway/pull/8)
    - [api-dotnet](https://github.com/blindnet-io/api-dotnet): no readme, PRs waiting for review
    
## READMEs

I've updated the following projects to reflect their new naming, fix links, and other missing parts:

- [sdk-java-client](https://github.com/blindnet-io/sdk-java-client): see https://github.com/blindnet-io/sdk-java-client/commit/7b49a03e5a230f6d196b06f130ce60d039ceac5c
- [sdk-javascript-client](https://github.com/blindnet-io/sdk-js-client): see https://github.com/blindnet-io/sdk-javascript-client/commit/354e6a04fe8cc9523cef816b29103aad541d263d
- [sdk-java-server](https://github.com/blindnet-io/sdk-java-server): see https://github.com/blindnet-io/sdk-java-server/pull/2 and https://github.com/blindnet-io/sdk-java-server/commit/5ca6cb779810434957c768ad8aebf14b4aa7efa9
- [sdk-dotnet-core-server](https://github.com/blindnet-io/sdk-dotnet-core-server): see https://github.com/blindnet-io/sdk-dotnet-core-server/commit/7079d185a69a26baf89a57236435cc11c438aaf4
- [sdk-dotnet-framework-server](https://github.com/blindnet-io/sdk-dotnet-framework-server): see https://github.com/blindnet-io/sdk-dotnet-framework-server/commit/213893ef8841df93117e4575cae690d09224743a
- [sdk-php](https://github.com/blindnet-io/sdk-php-server): see https://github.com/blindnet-io/sdk-php/commit/12ab7f95cfbaff444874907a941413f7b4fb9333
- [sdk-node](https://github.com/blindnet-io/sdk-node-server): see https://github.com/blindnet-io/sdk-node/commit/3afb3d04772c2b985ee99728b47101eea6cd0b36
- [quickstart-react](https://github.com/blindnet-io/quickstart-client-javascript-example): see https://github.com/blindnet-io/quickstart-react/commit/2d51686215828b81c29bb8374aca0f6092a3cd75
- [demo-token-generator](https://github.com/blindnet-io/quickstart-token-generator-javascript): see https://github.com/blindnet-io/demo-token-generator/commit/cb45152cb4348fa0b25cf0917dda54b628e65a4c

The following READMEs are still missing or incomplete:
- [sdk-java-server](https://github.com/blindnet-io/sdk-java-server): missing install instruction and a Javadoc (see https://github.com/blindnet-io/sdk-java-server/pull/2)
- [api-dotnet](https://github.com/blindnet-io/api-dotnet): proprietary, lower priority

Globally, the blindnet encryption engine is insufficiently documented and lacks automation. Yet, we are now considering this a low priority as our main focus is on the devkit. This will be addressed when the encryption features are added to the DevKit (with or without reusing these repos).

## Checklists

I'll review each checklist one by one when possible & necessary. As each of them is its own issue, it doesn't need this epic to stay open.
