### ISSUE TITLE
⚪️ Create a discussion space

### ISSUE THREAD

**Issue by nweldev** [blindnet-io/devrel-management#96]
> Request from @Vuk-BN - should be @noelmace next priority after https://github.com/blindnet-io/product-management/issues/980 & https://github.com/blindnet-io/product-management/issues/963, and "_[replace](https://github.com/blindnet-io/product-management/issues/964#issuecomment-1271803691)_" https://github.com/blindnet-io/product-management/issues/964.

## Description

Create and quick start a new and easy-to-join space for 3rd-party developers to ask questions and interact with blindnet employees.

### Reasoning

- blindnet needs a way to efficiently interact with 3rd-party developers and clients without affecting this task to anyone in particular (should be mostly handled by @blindnet-io/engineering as a team)
- blindnet needs a solution to answer questions regarding its product while development and documentation are in progress (and therefore incomplete)
- Slack won't be enough.
- GitHub issues are too complex / not really adapted for this

### Intended outcome

Any technical person working for a client of blindnet can easily find an answer to any question they have related to DevKit.

## Sub-tasks

- [ ] determine which tool to use (e.g. Discourse, GitHub discussions)
    - write a DR about it
    - GitHub discussions seem to be the better option so far according to @Vuk-BN 
- [ ] set-up the discussion space (install, configure, etc.)
- [ ] write some FAQ, so the discussion space isn't empty

## Stakeholders

- @Vuk-BN as the requester - track and guide decisions
- @blindnet-io/engineering as future main contributors to this space - contribute to the decisions and related technical actions
- @earvinblindnet as the lead sales representative - track progress and ask questions so he can efficiently direct clients to this new space, and possibly contribute to it when necessary
