### ISSUE TITLE
📑 [Epic]: Tech Events - S2 2022

### ISSUE THREAD

**Issue by nweldev** [blindnet-io/devrel-management#97]
## Description

All Tech Events related stuff for S2 2022 (from Jully to December).

### CFPs

> See https://github.com/scraly/developers-conferences-agenda
>
> Cf. talks with a [propose or following status](https://github.com/orgs/blindnet-io/projects/16/views/1)

- [x] [Devfest Nantes](https://conference-hall.io/public/event/CfucIjaXxrZThJE0POR3): Until 2022-06-19
- [x] [Forum PHP](https://afup.org/event/forumphp2022): Until 2022-06-20
- [x] [Devfest Strasbourg 2022](https://conference-hall.io/speaker/event/wgaja45IBdGT4sw4CXDB): Until 2022-06-30
- [x] [JUG Summer Camp](https://conference-hall.io/public/event/Ag6h1yHTsrdzHsPni5o9?mc_cid=9f3f4517b6&mc_eid=UNIQID): Until 2022-07-01
- [x] [BDX I/O 2022](https://conference-hall.io/public/event/OJC5Ou5YJodfetgSJCa3): Until 2022-07-31
- [x] [Codeurs en seine](https://conference-hall.io/speaker/event/Uv6XULhgmt7z2YuoJ8nq): Until 2022-09-16

### Talks

- [ ] blindnet-io/talks#2
- [ ] blindnet-io/talks#3
- [x] blindnet-io/talks#4
- [ ] blindnet-io/talks#1
- [x] blindnet-io/talks#5
- [x] blindnet-io/devrel-management#78
- [x] blindnet-io/talks#6

### Conferences

- [ ] LunaConf (Sept 30 :gb:): blindnet-io/talks#2
- [ ] PHP Forum (Oct 14 :fr:): blindnet-io/talks#2
- [ ] Codeur en Seine (Nov 17 :fr:): blindnet-io/talks#3

#### Online / Async

- [x] blindnet-io/devrel-management#37
- [x] blindnet-io/devrel-management#36

### Sponsoring

> TBD

### Misc

- [x] blindnet-io/devrel-management#39

**Comment by nweldev** [comment]
For now, only LunaConf and PHP Forum selected me (with my co-speaker) to give a talk during S2 2022: https://github.com/blindnet-io/talks/issues/2

TODO:

- We'll soon stop proposing https://github.com/blindnet-io/talks/issues/2, and need a successor. https://github.com/blindnet-io/talks/issues/5 wasn't a good enough idea, so we'll see if https://github.com/blindnet-io/devrel-management/issues/78 can be a better candidate.
- I believe https://github.com/blindnet-io/talks/issues/3 and https://github.com/blindnet-io/talks/issues/4 were only a one-time thing as no other event seems interested
- We need to find a better title and abstract for https://github.com/blindnet-io/talks/issues/1

However, the DevKit adoption is now my main focus (with workshops, etc.), before awareness. Such contents might not be suitable for such events for now (product promotion / not enough "generic" material to share), but I'll still see if I can write an abstract to answer CFPs and get feedback.

As this is an epic for the whole 2nd semester, I'm moving it to the Q4 milestone.
